remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Youbin's Homepage
description: Portfolio of Digital Humanities COML 1650 of Fall 2024
